### ISSUE TITLE
reveal style visibility: hidden doesn't change on scroll

### ISSUE THREAD

**Issue by FernandoBoza** [rnosov/react-reveal#1]
I downloaded the latest package from npm and tried the quick snippet 

` <Reveal effect="animated fadeInLeft">`
      `<div>Markup that will be revealed on scroll</div>`
 ` </Reveal>`

and won't work for me. 

Mac, Chrome V 58, React v15.5.0

**Comment by FernandoBoza** [comment]
found the issue, the element needs to scroll with in the middle of the screen and since i pasted it in the footer it wouldn't reveal. I also want to ask if is normal to still not reveal even when loaded in the same location

**Comment by rnosov** [comment]
There was a fix for server side rendering that I made optional now. It might be the issue you were facing. Check the latest version ^0.2.0 to see if it works better for you.
