### ISSUE TITLE
fade in viewport

### ISSUE THREAD

**Issue by bluetch** [rnosov/react-reveal#10]
Hello, I would like to ask how to run fade when component really scroll into viewport? like the demo, I have setup with readme, but always fade with whole component, even no scroll, thank you.

**Comment by getnorthern** [comment]
I get a similar thing - components seem to appear as blocks (or sometimes individually) - there seems to be inconsistencies in the timing of the fade in as the user scrolls down the page, even when using the default Fade settings.

**Comment by rnosov** [comment]
I've changed the timing algorithm from debounce to throttle in the `1.0` version so it might resolve your issue. Also, there is a `fraction` prop that you can play with. It basically tells `react-reveal` what percentage of the element must be on screen in order to trigger the reveal.
