### ISSUE TITLE
'withReveal' is not defined

### ISSUE THREAD

**Issue by elzie** [rnosov/react-reveal#103]
Can anyone tell me why I get this error and how to fix it? 

`
Failed to compile
./src/components/FrontpageNewsFeature.js
  Line 15:17:  'withReveal' is not defined  no-undef

Search for the keywords to learn more about each error.
`

here is my code: 

`
import React from 'react';
import Fade from 'react-reveal/Fade';

import styled from 'styled-components';

const Container = styled.div`
  background: none;
  min-height: 575px;
  border-bottom: 1px solid black;
`;
const MyText = styled.div`
  font-size: 16px;
  color: red;
`;
const NewText = withReveal(MyText, <Fade bottom />);
class FrontpageNewsFeature extends React.Component {
  render() {
    return (
      <Container>
        <div>Nyheder</div>
        <MyText>My Text</MyText>
        <NewText>New Text with Reveal</NewText>
      </Container>
    );
  }
}

export default FrontpageNewsFeature;
`

**Comment by jjbartek** [comment]
You need to import the withReveal function before.

`import withReveal from 'react-reveal/withReveal';`

**Comment by elzie** [comment]
Awesome - thank you very much! :)

**Comment by jdtzmn** [comment]
Just thought I should mention that the import statement above is not written in the online web documentation anywhere.
