### ISSUE TITLE
Possible to disable "debounce"

### ISSUE THREAD

**Issue by i8ramin** [rnosov/react-reveal#11]
The earlier versions of this code used to trigger the reveal while a scroll was taking place. After upgrading to the latest version, I am noticing that the animation does not take place until the window scrolling has come to a complete stop. I am guessing this was done for performance reasons, but I am wondering if there is a way to disable this? My client is asking for the reveal animation to happen as soon as possible, even while the user is still scrolling. Can this be done?

**Old behavior (instant reveal)**
https://cl.ly/2m1j3T013X1x

**New behavior (delayed/denounced reveal)**
https://cl.ly/2u0u1A0z2O2T

**Comment by jhummel** [comment]
Same. This is really noticeable when using physics scrolling on a trackpad or Apple magic mouse and you 'flick' to scroll. You can end up with many elements animating at once after the scrolling stops.

**Comment by raygesualdo** [comment]
@rnosov Using lodash's debounce could potentially solve this. It has a [maxWait](https://lodash.com/docs/4.17.4#debounce) option which would allow it to fire after X milliseconds even if the user isn't done scrolling. That maxWait time could even be a component prop if you wanted to make is user-configurable.

**Comment by rnosov** [comment]
I've replaced debounce with throttle in `1.0` so if you upgrade to the latest version, it should hopefully resolve this issue.
