### ISSUE TITLE
Does not reveal until scroll stops

### ISSUE THREAD

**Issue by strin** [rnosov/react-reveal#12]
While the scrollbar is moving, the element does not show up.

**Comment by elinanen** [comment]
@strin To me it looks like the elements sometimes show up even during scrolling, but there's a random unexplainable delay every now and then (which is not due to delay props).

**Comment by ZhengRaymond** [comment]
+1

**Comment by rnosov** [comment]
Perhaps it was an issue with debounce which I removed in version `1.0`. Upgrade to the latest version and it should be much better.
