### ISSUE TITLE
I'm Getting This Error While Installing The React-Reveal And I'm Unable To Understand How To Solve It 

### ISSUE THREAD

**Issue by AdityaKirad** [rnosov/react-reveal#132]
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: lucario-webpage@0.1.0
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-reveal@1.2.2
npm ERR! node_modules/react-reveal
npm ERR!   react-reveal@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Aditya Kirad\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Aditya Kirad\AppData\Local\npm-cache\_logs\2022-05-17T05_30_28_333Z-debug-0.log```

**Comment by LucaNerlich** [comment]
React-Reveal is basically deprecated at this point. It did not get any updates for years. In its package.json it declares a dependency to react 15 - 16, you are using react 18 and node >= 16.

you can run `npm i --legacy-peer-deps` (as it tells you ;-) ) to have npm somewhat ignore this error, but it MIGHT lead to issues.

**Comment by Safnaj** [comment]
Try force install.

`npm i react-reveal -f`

**Comment by Rafidimas17** [comment]
> Try force install.
> 
> `npm i react-reveal -f`

thank you, that's work

**Comment by PremShinde-2013** [comment]
try force install it really works
npm i react-reveal -f

**Comment by Nithin-Kamineni** [comment]
this works for the development environment, but what if we want to deploy the application? react-reveal is not compatible with react 18.2.0. so the terminal in my deployment platform is throwing an error while installing npm packages. What must I do?

**Comment by HammadAhmed30** [comment]
> this works for the development environment, but what if we want to deploy the application? react-reveal is not compatible with react 18.2.0. so the terminal in my deployment platform is throwing an error while installing npm packages. What must I do?

yes i am facing the same problem.

**Comment by SiddharthaMishra-dev** [comment]
> try force install it really works npm i react-reveal -f

Not sure, but what if it broke other packages ?

**Comment by AdityaKirad** [comment]
> > try force install it really works npm i react-reveal -f
> 
> Not sure, but what if it broke other packages ?
well I have moved on to better animation libraries which works with react 18 but thank all of guys for you support

**Comment by AdityaKirad** [comment]
> > try force install it really works npm i react-reveal -f
> 
> Not sure, but what if it broke other packages ?

well I have moved on to better animation libraries which works with react 18 but thank all of guys for you support

**Comment by malachi43** [comment]
it having trouble pushing my react app to production because of react-reveal deprecation. What do I do

**Comment by SiddharthaMishra-dev** [comment]
> it having trouble pushing my react app to production because of react-reveal deprecation. What do I do 

It is best to move to new library. For my project , I use react-awesome-reveal. It is not as feature rich as react-reveal, but it gets the work done. No problem

**Comment by Jonaathan-Santos** [comment]
Tente utilizar react-awesome-reveal ao invés react-reveal.

https://www.npmjs.com/package/react-awesome-reveal#installation

**Comment by LovkashGarg** [comment]
guys I am getting same error while deployment phase what to do?
