### ISSUE TITLE
cascade doesn't work if there is only one list item

### ISSUE THREAD

**Issue by rokit** [rnosov/react-reveal#14]
I tried this for Fade, not the others.

this was the code I used:
```
<Fade right cascade tag="ul">
	{this.props.details.list.map((item) => 
		<li key={Math.random(100000000000)}>
			<img alt="bullet pont" src={bullet} />
			<span>{item}</span>
		</li>
	)}
</Fade>
```

**Comment by rnosov** [comment]
I've fixed this problem in `1.0` version. The only thing is that in the latest version the `tag` prop is no longer supported so you'd have to manually wrap `li`'s in the `ul` tag.
