### ISSUE TITLE
Fade only working once chrome browser stops scrolling

### ISSUE THREAD

**Issue by miniturny** [rnosov/react-reveal#16]
As per title, it seems to be working fine on safari and firefox at this point, on both mobile and firefox. Let me know if there is some prop I can use to fix it.

**Comment by rnosov** [comment]
Hmm, `react-reveal` should work really well with Google Chrome as it has excellent support for animations. I'd hazard a guess  that perhaps:
- some extension is interfering with `react-reveal` event loop
- may be you have some code in your app that messes up `react-reveal`

If you could try [Fade example](http://www.react-reveal.com/examples/common/fade/) (scroll to the bottom of the page) with all extensions disabled and see if the problem persists. It would also help if you report your Browser/OS version as I can't reproduce this issue on my computer.

**Comment by miniturny** [comment]
After further testing, it turns out this occurs on the other browsers as well, just more often on the chrome browser. I have looked into this issue through your recent issues, and it seems this was a task that was fixed in 1.0 ?? I'm not sure if it has worked. Worth noting that i am wrapping images in the fade component. Are there any

**Comment by rnosov** [comment]
Okay I found [similar issue](https://github.com/aFarkas/lazysizes/issues/139). It seems to be that there is some performance optimization in Chrome that you're probably experiencing. They say that fixing image dimensions might help. 

Does it happen only on a mobile or on a desktop too? There seem to be a fix suggested for mobile (touchmove/touchend). I'll try to reproduce this issue to see what can be done.

**Comment by miniturny** [comment]
I see, the issue does in fact only happen on desktop.i posted some details of how i coded it [here](https://stackoverflow.com/questions/48558498/react-reveal-only-working-when-scroll-is-stopped-chrome). Let me know! it would be cool if this was able to be resolved, implementing scrollreveal.js pales in comparison in terms of simplicity.

**Comment by miniturny** [comment]
Further info, i seem to have locked down the problem more exactly. So i am importing a lottie animation into my project, and once it is loaded it is somewhat pushing the rest of the fading views downwards (This is to be fixed with a placeholder image). If i wait for this to happen, and for the animation to start, there is no problem. However, if i begin scrolling before this process finishes, i am getting the problem that i explained

**Comment by rnosov** [comment]
Okay, I've tried reproducing this issue but everything worked perfectly fine. I think the problem is not with `react-reveal` but with some other piece of code in your application that is stressing your browser. It looks like Google Chrome likes to deprioritize scroll events under heavy load. `react-reveal` needs to receive timely scroll events and therefore is being affected. If you point me to your entire app I can have a second look but I think the root cause of this issue lies somewhere else.
