### ISSUE TITLE
React reveal with React Component

### ISSUE THREAD

**Issue by meridj** [rnosov/react-reveal#17]
Hi,

Thank you so much for your librarie.

But have any example with a Custom React Components use case please ?

**Comment by rnosov** [comment]
Well I'm planning to document this use case a bit more thoroughly. Basically you can either:
- Wrap your component in a `div` tag:
```jsx
<Fade>
  <div>
     <YourComponent />
  </div>
</Fade>
```
- [Expose DOM ref in your component](https://reactjs.org/docs/refs-and-the-dom.html#exposing-dom-refs-to-parent-components) 
```jsx
<Fade refProp="inputRef">
  <YourComponent />
</Fade>
```
`inputRef` is taken from example docs but could be anything you want

- use `withReveal` Higher Order Component. That's the proper way to inject reveal functionality in custom component. Docs are coming soon but you can take a look at [this source](https://github.com/rnosov/react-reveal/blob/site/src/home/slides/Open.js) to get the idea how it works.

**Comment by meridj** [comment]
Greaat ! :+1:
