### ISSUE TITLE
Unable to Run the project

### ISSUE THREAD

**Issue by darshana96** [rnosov/react-reveal#18]
I have update the .bashrc and install the package. I am getting following error.
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "add-module-exports" specified in "/Users/webwerks/Documents/Darshana/LoomiClient/Workspace/loomitNeoGit/loomimarketingwebsite/.babelrc" at 0, attempted to resolve relative to "/Users/webwerks/Documents/Darshana/LoomiClient/Workspace/loomitNeoGit/loomimarketingwebsite"

**Comment by rnosov** [comment]
Are you installing `react-reveal` via NPM? You should install it like so:
```sh
npm install react-reveal --save
```
and if you need `Fade` import it like this (from the docs) 
```jsx
import Fade from 'react-reveal/Fade';
```
It looks like what you're trying to do is to import it from source files which wouldn't work as you need the transpiled output.

**Comment by darshana96** [comment]
Yes I am doing the same way. I shall try once again and update you.

**Comment by rnosov** [comment]
Hmmm, if it's installed via npm then `react-reveal` errors should generally come from `node_modules` folder. I see that's not the case in here. Perhaps, you have some problem with your Babel configuration (say `add-module-exports` is missing) ?

**Comment by darshana96** [comment]
Following thing where added for these changes : 
1. .bablerc 
{
  "presets": [
    "react",
    "es2015",
    "stage-2"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ]
}

2. webpack.config.js
loaders:[
{
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
            },
]

3. npm install babel-plugin-transform-runtime babel-preset-es2015 babel-preset-stage-2 --save

4. npm i babel-plugin-add-module-exports babel-preset-es2015 babel-preset-stage-2 --save

Worked for me. 
Cheers
