### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sayax** [rnosov/react-reveal#2]
Could you update this? My app throws warning 
Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs

**Comment by rtmalone** [comment]
Created PR #3 for the upgrade

**Comment by rnosov** [comment]
Should be fixed by 8781e9588cfb5b547e3cae1ead862622d78a536d commit. Upgrade your react-reveal version to ^0.2.0.
