### ISSUE TITLE
using fade, elements sometimes do not fade in

### ISSUE THREAD

**Issue by eballeste** [rnosov/react-reveal#20]
i've noticed that sometimes if i refresh the page and scroll down, the fade effects will not get triggered

only after clicking anywhere will scrolling and fading in work again

**Comment by eballeste** [comment]
only happens in chrome

**Comment by eballeste** [comment]
i noticed that if i wait a couple of seconds, they eventually will show up, so it's like something is randomly causing a crazy delay before the components fade in and it only seems to happen in chrome

**Comment by rnosov** [comment]
Okay, I think I've cracked this issue. I've pushed `1.1.9-beta.1` to npm which should work much better. You can install it via npm by running:
```sh
npm i react-reveal@beta
```
Let me know if you're still having this problem with the latest beta.

**Comment by eballeste** [comment]
To be honest I do have a very expensive paperjs animation that I optimized
as much as I could but it's way off screen by the time I reach the div that
contains the revealable content. Im away from my machine but will test
later tonight! Thank you for taking a look at this so quickly and for
giving me something to look into if the issue still persists. 👏

**Comment by eballeste** [comment]
i think it worked, haven't been able to reproduce 👏👏👏👏

**Comment by rnosov** [comment]
Thank goodness, this problem was really driving me mad as I wasn't able to reproduce it myself. I'll push the fix in `1.1.9` then. BTW, consider giving a star to `react-reveal` if you end up using it.
