### ISSUE TITLE
Server Side Rendering causing issues on v. 1.1.10

### ISSUE THREAD

**Issue by elvisguillen** [rnosov/react-reveal#21]
Hey, great work on this plugin! Had some issues with Server Side Rendering after deploying to Netlify today with version 1.1.10, specifically getting the 'window' is not defined error during build - 

<img width="408" alt="screen shot 2018-03-05 at 2 46 19 pm" src="https://user-images.githubusercontent.com/4971180/36996136-04b9be9a-2084-11e8-8605-48ac58c180c8.png">

After going back to version 1.1.7 it works great with no build errors or 'window' issues. 

Thanks again!

**Comment by rnosov** [comment]
Yeah, sorry about the issue. I was about to patch it but I got bogged down with `1.2.0` release testing. Anyway, I've released `1.1.11` which fixes this bug for `1.1.x` branch and `1.2.0` release which doesn't have it at all. You should probably upgrade to `1.2.0` as it should have much better performance. I've also made the initial ssr fadeout effect optional as opposed to default behaviour ( check the docs how to get it back if you need it)
