### ISSUE TITLE
Running into a weird error with GatsbyJs

### ISSUE THREAD

**Issue by mhdevnet** [rnosov/react-reveal#25]
Hi Guys,

Everytime i try to use this package I get the following error:

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: symbol.`

For reference i'm using GatsbyJs. Is there any logical reason for this happening?

**Comment by rnosov** [comment]
Hmm, a really weird error message. Can you try wrapping the revealed content a with `<div>` tag like

```jsx
<Fade>
  <div>Revealed content</div>
</Fade>

and see if the problem persists. Also make sure you importing Fade class like so:
```jsx
import Fade from 'react-reveal/Fade';
```

and see if the problem persists

**Comment by mhdevnet** [comment]
Awesome! Works like a charm! Thanks @rnosov
