### ISSUE TITLE
Animation duration

### ISSUE THREAD

**Issue by sboudouk** [rnosov/react-reveal#27]
Hello.

I'm looking for a way to change the animation durations, since nothing mention it in the documentation (or at least I did not find it), I'm opening this as an "issue".

Thanks for answering and for this game-changer package.

**Comment by rnosov** [comment]
Have a look at this page:
https://www.react-reveal.com/docs/props/
There is prop called `duration` which sets animation duration in milliseconds ( 1000 be default )

**Comment by sboudouk** [comment]
Thanks, closing.
