### ISSUE TITLE
'render' is not defined  no-undef

### ISSUE THREAD

**Issue by mowmiheniek** [rnosov/react-reveal#28]
Hi,
I tried using carousel in my project and i got that error.
I start with a very simple Carousel tutorial.
I not change anything.
I only added:  import React from 'react';
React version 5.6.0

**Comment by rnosov** [comment]
The Carousel tutorial is the most advanced one. I suggest you to try just simple reveal effects first.
Perhaps it might not be very clear from the tutorial but the code from the `render` method shown there must be plugged somewhere in your component `render` method.
If you have say `Home` react component which renders homepage it surely has to have a `render` method. It is there that you insert `Carousel` component with the styled UI. A generic `render` method is shown in the tutorial. If you just copy code from the tutorial it won't work as it has now way knowing you internal project structure and the rest of component is missing ( you're supposed to provide it yourself ).

**Comment by mowmiheniek** [comment]
Thank you. I'm just starting my adventure with React. Thank you.
