### ISSUE TITLE
Cascade effect doesn't recalculate variable height of revealed element (form errors)

### ISSUE THREAD

**Issue by michalgrudzien** [rnosov/react-reveal#30]
Hi, I'm using react-reveal for smooth displaying of form errors.
Error labels vary depending on the effect of validation, therefore the element which is revealed (with cascade prop) may have different height each time it is revealed. Some errors wrap in one line, while others are broken into more lines. 

If revealing of a larger element occurs after a smaller one was revealed previously in that component, it does not seem to recalculate height to current child and causes overflows.
Is there anything that could be done to trigger this recalculation?

Cheers

**Comment by rnosov** [comment]
It does recalculate the heights even when they are being changed on-the-fly. You can try running the following modified Fade example ( if you're trying it in the live editor make small change like adding a space to trigger update). In the example below the interval func adds 1px to the height every 100ms. It seems to cover your case. Perhaps you're modifying error labels directly bypassing React VDOM or something like that. In React all changes must go through state. Feel free to post some counter example that has this issue but I can't reproduce it for now.

````jsx
import React from 'react';
import Fade from 'react-reveal/Fade';

class FadeExample extends React.Component {
  constructor(props) {
    super(props);
    this.state = { show: false, h:100 };
    this.handleClick = this.handleClick.bind(this);

  }
  handleClick() { 
    setInterval( ()=> this.setState({ h: this.state.h + 1 }), 100 )
    this.setState({ show: !this.state.show });
  }
  render() {
    return ( 
      <div>
        <Fade left collapse cascade when={this.state.show} duration={5000}>
          <div> 
            <h2 style={{border:'1px solid red',height:this.state.h + 'px'}}>              
              React Reveal
            </h2>
            <h2>React Reveal</h2> 
            <h2>React Reveal</h2>
          </div>
        </Fade>
        <button
          className="btn btn-success my-5"
          type="button"
          onClick={this.handleClick}
        >
          { this.state.show ? 'Hide' : 'Show' } Message
        </button>
      </div>
    );
  }
}

export default FadeExample;
````
