### ISSUE TITLE
Disable animation exceeds the element involved

### ISSUE THREAD

**Issue by clementloridan** [rnosov/react-reveal#31]
Hi, 

I used Fade component but when i scrolled the page and I refresh I would like disable animation.

An idea?

Thk

**Comment by rnosov** [comment]
Well a bit unusual use case but I suppose you could use cookies or LocalStorage to check if a user  visited your web site before. (**update**: You should use `onReveal` event handler to check if the element is actually revealed and then save it in cookies or LocalStorage) . If you did that and saved it to variable named `hasVisited` you could do on of several things:
- set disabled prop to true like so 
````jsx
<Fade disabled={hasVisited} onReveal={ () => {/* set hasVisited to true  */} }>
  <div>Your Content </div>
</Fade>
````
The `disabled` prop is mostly used internally and is the simplest way but it might have slight side effects.
- Remove reveal elements entirely
````jsx
{ hasVisited ? <div>Your Content </div> : <Fade onReveal={ () => {/* set hasVisited to true  */} }><div>Your Content </div></Fade>  }
````
The last option is the sure way to disable all animations
