### ISSUE TITLE
Reset animation when component is out of viewport

### ISSUE THREAD

**Issue by mckelveygreg** [rnosov/react-reveal#32]
Is it possible to reset animations once the component leaves the viewport?
The use case would be, a user has loaded the page, but would like to show someone else. Instead of refreshing, they would be able to just scroll through the content again.

Thanks

**Comment by rnosov** [comment]
At the moment it's not possible. You can sort of simulate this effect by unmounting and mounting again the component that has reveal animations to see animations all over again ( with a timer, keystroke or button ). The reset feature can be potentially added to the library but it will make it somewhat more complex and I find the resetting animations to be quite annoying to be honest. I don't see much problem with refreshing the page to see these effects again either. So far I can't see a compelling use case for it.

**Comment by mckelveygreg** [comment]
K, I'll close. Thanks for your reply and your package!
