### ISSUE TITLE
Add delay to when the animation effect should start

### ISSUE THREAD

**Issue by balazsorban44** [rnosov/react-reveal#38]
Hi, I was wondering if there is a way to achieve some delay after the `when` prop is set to `true`. I have an array of images. This array first has zero elements. and then when I fetched the images, it gets filled with the images' URLs. So in my `when` prop I simply set `array.length`. But I would like to wait a few 100 milliseconds before it happens. Is there a built-in method for this, or should I create an internal state which uses `setInterval` when `array.length` is not zero anymore?

**Comment by PeterKottas** [comment]
the prop name is delay ;)

**Comment by caseydev** [comment]
Yea its fine but how can add delay dynamically like using loops. Should like 5s,10s,15s and so on
