### ISSUE TITLE
react-reveal throwing console PropTypes warning on import

### ISSUE THREAD

**Issue by b0ts** [rnosov/react-reveal#4]
Hey guys,
Love react-reveal and using it on [sweetlightstudios website.](https://github.com/b0ts/react-redux-sweetlightstudios-website) 

When I import react-reveal via:
import Reveal from 'react-reveal';

The console throws a warning:
proxyConsole.js:56 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Best,
b0ts

**Comment by rnosov** [comment]
Should be fixed by 8781e9588cfb5b547e3cae1ead862622d78a536d commit. Upgrade your react-reveal version to ^0.2.0
