### ISSUE TITLE
Fade is not working on Iphone

### ISSUE THREAD

**Issue by Gilbert1391** [rnosov/react-reveal#40]
The Fade effect is not working on my Iphone, however when I use Chrome toggle device toolbar and select Iphone, it does seem to be working, although there's a strange behavior with the effect. 

You can check the site here https://dashboardbox.netlify.com/#/ and select one of the movies and you will see what the behavior I'm talking about (in mobile mode). In my Iphone I never get to see the content inside the <Fade></Fade> component. Maybe it's related to my css?

**Comment by tgmarinho** [comment]
I have the same problem in here, I was using it in my startup, but I am launching my business right now,  so I remove this lib. =( But I really appreciate this job!

**Comment by rnosov** [comment]
I can't reproduce it neither on iphone nor on chrome
