### ISSUE TITLE
Dynamic and/or all import support?

### ISSUE THREAD

**Issue by minotaurrr** [rnosov/react-reveal#41]
Hi guys,

I'm trying to import react-reveal dynamically depending on user input - is this doable at all?

I was hoping I could do something like `import * as ReactReveal from 'react-reveal'` then use it as `<ReactReveal.Fade>`

I'm taking in a user input to choose what effect they want so in the end I'm hoping it to be something like..
```
const Reveal = `ReactReveal.${this.props.effect}`
return (<Reveal />);
```

**Comment by rnosov** [comment]
As far as I know this is a Webpack limitation. To be honest I'm struggling to see a use case for this.
