### ISSUE TITLE
withReveal breaks flexbox styling with styled-components

### ISSUE THREAD

**Issue by sfkiwi** [rnosov/react-reveal#42]
I am using flexbox styling with styled-components. According to the react-reveal docs, the module should work out of the box with styled-components.

An example of where the problem comes up is:

I have a container div 
`````
import ProjectCard from './ProjectCard'

const Container = styled.div`
   width: 80%;
   max-width: 1200px;
   padding: 100px;

   display: flex;
   flex-direction: row;
   justify-content: space-evenly;
   align-items: center;
`

const ProjectSection = ({projects}) => (
    <Container>
      {projects.map(({image, title, description}, i) => (
        <ProjectCard key={i} image={image} title={title} description={description} />
      ))}
    </Container>
)
`````

with 3 internal divs

`````
const Card = styled.div`
   /* style */
   min-height: 400px;
   min-width: 100px;
   max-width: 400px;
   background-color: white;

   /* flex */
   display: flex;
   flex-basis: 25%;
   flex-direction: column;
   justify-content: flex-start;
   align-items: center;
`;

/* apply fade in animation */
const Card = withReveal(card, <Fade bottom />)

const ProjectCard = (props) => {

  return (
    <Card>
      <Image src={props.image} />
      <h2>{props.title}</h2>
      <p>{props.description}</p>
    </Card>
  )
}

export default ProjectCard
`````

This layout works fine without `withReveal` but when I wrap them in the HOC an extra div gets added which breaks the parent->child relationship in flexbox and the internal divs lose their layout, in particular the flex-basis.

The docs seem to say that this is taken care of using the refProp but then goes on to say that this is already done automatically when using styled-components.

**Comment by sfkiwi** [comment]
The workaround I used to get around this is to wrap the withReveal div in between two other divs. That way you can maintain the flexbox styling.

**Comment by anuraghazra** [comment]
> The workaround I used to get around this is to wrap the withReveal div in between two other divs. That way you can maintain the flexbox styling.

can you please explain the code, i have the same issue but when i wrap the component with withReveal HOC component another div is created and breaks the layout can you provide me code to solve the issue.
