### ISSUE TITLE
Error on Android 4.1 Browser and Chrome Desktop 42

### ISSUE THREAD

**Issue by VoloshchenkoAl** [rnosov/react-reveal#44]
Stack trace:
`Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '@keyframes react-reveal-956029157852754-1{from {opacity: 0; transform: translate3d(0, -100%, 0);}
     to {opacity: 1;transform: none;} }'.
at Error (native)`

It is only in production.

**UPD**
The problem in a version of a package in npm:
`function animation(e) {
    if (!sheet)
        return "";
    var n = "@keyframes " + (name + counter) + "{" + e + "}", t = effectMap[e];
    return t ? "" + name + t : (sheet.insertRule(n, sheet.cssRules.length), effectMap[e] = counter, "" + name + counter++)
}`

**Comment by VoloshchenkoAl** [comment]
Please, update version in npm repo with https://github.com/rnosov/react-reveal/pull/29 changes.

**Comment by rnosov** [comment]
hmm it shouldn't affect the production unless you're using custom rules. But I'll release the new version
