### ISSUE TITLE
how to add animation when component is unmouting 

### ISSUE THREAD

**Issue by sundariya786** [rnosov/react-reveal#46]
I start using react-reveal and it looks very good but I want animation when a component is mounting as well as when a component is unmounting also. Is there any to animate when a component is removing from DOM.

**Comment by richvoronov** [comment]
use [react-transition-group](http://reactcommunity.org/react-transition-group/transition-group/). Also you can check react-reveal [documentation](https://www.react-reveal.com/examples/advanced/todo/)

**Comment by rnosov** [comment]
you can also check https://www.react-reveal.com/examples/ . Check the show/hide button to get the idea how you can get the exit animations
