### ISSUE TITLE
Callback on animation done

### ISSUE THREAD

**Issue by gabrielmicko** [rnosov/react-reveal#48]
Is there an option to subscribe to animation end? For example: ```<Flip bottom onDone={this.doSmth}>``` ?

**Comment by rnosov** [comment]
There is callback called onReveal. There is example at the bottom of the docs page
https://www.react-reveal.com/docs/props/

**Comment by gabrielmicko** [comment]
It's not the same, but better then nothing, thanks! :)

**Comment by rnosov** [comment]
There is another prop called `wait` that allows you to specify the waiting time in milliseconds before `onReveal` callback is fired. What I found that you wouldn't typically want to wait until the animation fully finishes but perhaps fire the callback just before the end. It's hard to pinpoint exact moment so you would be better off developing your own formula. But if you just want to fire callback right after animation ends then simple formula would be `wait = delay + duration`  or 1000 milliseconds by default.
