### ISSUE TITLE
'cannot read offset of "

### ISSUE THREAD

**Issue by EmilioHerrera** [rnosov/react-reveal#7]
Hi,
I am getting 'cannot read offset of " when using react-reveal which completely kills performance. Any ideas or tips? thanks in advance!!!

**Comment by rnosov** [comment]
Hmm, `react-reveal` doesn't use `offset` property anywhere ( it uses `offsetTop`, `offsetParent`, `pageYOffset` though). Are you trying to get react-reveal` element offset with something like JQuery `offset()` method by any chance? If you do, I can see a number of reason why this might not work.
Anyway, would you be able to post parts of your code showing your `react-reveal` usage? Especially, anything that has word offset in it.

**Comment by EmilioHerrera** [comment]
Sorry, my bad. The correct error is: "Uncaught TypeError: Cannot read property 'offsetHeight' of undefined
    at o.handleReveal"

This is the part of the code:

```

import Reveal from 'react-reveal';
import 'animate.css/animate.css';


const Post = (props) => (
  <Reveal effect={'animated slideInDown'} >
  <div className={`c-blogPost ${props.layout === 'blogpost' ? 'card' : 'col-lg-4 col-md-6 col-sm-12'}`}>
    {(props.type === 'normal' || !props.type) &&
      <div className={'c-blogPost--normal'}>
        <ComposerLink to={props.button.url}>
          <div className="c-blogPost__img">
            <div className="c-blogPost__img__inner">
              <div className="c-blogPost__img__overlay" />
                {!!props.img && <Media width={650} media={props.img} />}
            </div>
          </div>
        </ComposerLink>

        {props.date && <div className="c-blogPost__date">{props.date}</div>}
        <h3>{props.title}</h3>

        {props.subtitle &&
        <LinesEllipsis
          className="c-blogPost__subtitle"
          text={props.subtitle}
          maxLine="3"
          ellipsis="[...]"
          basedOn="letters"
          trimRight={true}
        />
        }

        {props.button && props.button.url &&
          <ComposerLink to={props.button.url}>
            <div className="c-blogPost__more">
              More
            </div>
          </ComposerLink>
        }
      </div>
    }

    {props.type === 'first' &&
      <div className={'c-blogPost--first'}>
        <h3>{props.title}</h3>
        <p>{props.text}</p>
        {props.button && props.button.title &&
          <ButtonLink
            url={props.button.url}
            type={props.button.type}
            text={props.button.title}
          />
        }
      </div>
    }
  </div>
  </Reveal>
);

```

**Comment by rnosov** [comment]
Okay, I think you're running into a race condition on `react-reveal` unmounting. I've just pushed 0.5.1 version on to npm which should fix this issue. Update to the latest version (0.5.1) and see if the problem disappears.

**Comment by EmilioHerrera** [comment]
I think is fixed! Thank you!! I will report back if I encounter the issue again.
