### ISSUE TITLE
cannot read property 'offsetTop' of undefined

### ISSUE THREAD

**Issue by manoj150283** [rnosov/react-reveal#8]
Hi, I am getting below error message while using react-reveal inside loop with custom css.

Uncaught TypeError: Cannot read property 'offsetTop' of undefined
    at getAbsoluteOffsetTop (D:\Projects\xyz\node_modules\react-reveal\dist\Reveal.js:1)
    at o.handleReveal (D:\Projects\xyz\node_modules\react-reveal\dist\Reveal.js:1)

Any help is highly appreciated :)

**Comment by rnosov** [comment]
Update `react-reveal` to the latest version `0.7.2` and the error should dissappear.

**Comment by smallstepstoday** [comment]
I am having this issue on 1.0.0. Do we have a regression?

**Comment by rnosov** [comment]
Hmm, to be honest it is definitely something different as I have lots of checks in place to address the original issue. Would you be able to post exact error description, alongside with browser and OS version.

If possible can you also post your markup and/or code ( some sort minimal code reproducing the issue would be ideal ). It might be some weird error like `offsetTop` is missing from SVG elements  in certain versions of Firefox

**Comment by jordanpurinton** [comment]
@smallstepstoday If in your case you are trying to wrap a custom component (which I was when I ran into this issue), try wrapping the custom element in a div or something.

So: 

```
<Fade>
    <div>
        <CustomThing/>
    </div>
</Fade>
```

**Comment by rnosov** [comment]
Ahh thanks @jordanpurinton, now I understand what's the issue. I've pushed a mitigation for it in `1.0.2`. So you don't really need to wrap custom components in a div.

**Comment by rnosov** [comment]
The original issue was due to unrelated race condition so that confused me a bit. I really wish people would file separate issues and post full console errors...
